[package]
name = "lucet-wiggle"
version = "0.6.2-dev"
homepage = "https://github.com/fastly/lucet"
repository = "https://github.com/fastly/lucet"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
authors = ["Lucet team <lucet@fastly.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lucet-wiggle-generate = { path = "./generate", version = "0.6.2-dev" }
lucet-wiggle-runtime = { path = "./runtime", version = "0.6.2-dev" }
wiggle-generate = { path = "../wasmtime/crates/wiggle/crates/generate"}
witx = "0.8.3"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
wiggle-runtime = { path = "../wasmtime/crates/wiggle/crates/runtime"}
wiggle-test = { path = "../wasmtime/crates/wiggle/crates/test"}
lucet-runtime = { path = "../lucet-runtime", version = "0.6.2-dev" }
tempfile = "3.1"
lucet-wasi-sdk = { path = "../lucet-wasi-sdk", version = "0.6.2-dev" }
lucetc = { path = "../lucetc", version = "0.6.2-dev" }
